#!/usr/bin/env python3
import sys
import linecache
import os

from BalayyaLang.utils import Thappulu, showHelp, err
from BalayyaLang.api import BalayyaLang


def main():
    if len(sys.argv) <= 1 or ('-h' or '-help' or 'help') in sys.argv:
        showHelp()

    filename = sys.argv[-1]
    if not os.path.isfile(filename):
        raise Thappulu(err.C404)
    elif os.path.splitext(filename)[-1] != '.simha':
        raise Thappulu(err.C405)

    script = BalayyaLang()
    script.run(filename)


if __name__ == '__main__':
    try:
        main()
    except Thappulu as thappu:
        print(thappu)
else:
    raise Thappulu(
        'Ilaga BalayyaLang ni vere languages lo import cheskune soukaryam prasthuthaniki ledu')
